project:
  type: website
  output-dir: docs

website:
  title: "adventofcode"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

